esphome:
  name: liveingroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "LOUISAP"
  password: "19831226lc"
  manual_ip:
    static_ip: 192.168.199.82
    gateway: 192.168.199.1
    subnet: 255.255.255.0
    dns1: 192.168.199.1


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "A Fallback Hotspot"
    password: "wlPOqwGHh7yH"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "19831226lc"

ota:
  password: "19831226lc"

time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/Shanghai"

light:
  - platform: fastled_clockless
    restore_mode: ALWAYS_OFF
    chipset: WS2812B
    pin: 12
    num_leds: 15
    rgb_order: GRB
    name: "color LED"
    id: 'led_livingroom'

# switch:
#   - platform: gpio
#     name: switch
#     pin:
#       number: 12
#       inverted: yes
#     id: 'led_livingroom'

binary_sensor:
  - platform: gpio
    pin:
      number: 4
    id: 'red_ray_livingroom'
    filters:
#     调整持续2s有感应到热度变化才触发高电平,触发高电平后10s才接受低电平输出
#     将HC-SR501的传感器灵敏度和封锁时间都调到最低，效果不错
      - delayed_off: 10s
      - delayed_on: 2s
    on_state:
      then:
      - lambda: |-
          auto time = id(sntp_time).now();
          if (id(red_ray_livingroom).state == 1 && (time.hour > 18 || time.hour < 18)) {
            auto call = id(led_livingroom).turn_on();
            call.perform();
          } else {
            auto call = id(led_livingroom).turn_off();
            call.perform();
          }
