esphome:
  name: nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "LOUISAP"
  password: "19831226lc"
  manual_ip:
    static_ip: 192.168.199.81
    gateway: 192.168.199.1
    subnet: 255.255.255.0
    dns1: 192.168.199.1


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu Fallback Hotspot"
    password: "gqlqqSTdY2bJ"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "19831226lc"

ota:
  password: "19831226lc"

#从sntp服务器获取日期
time:
  - platform: sntp
    id: sntp_time
    timezone: "Asia/Shanghai"

sensor:
  - platform: dht
    pin: 5
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 10s
    model: dht11

# switch:
#   - platform: gpio
#     name: switch
#     pin:
#       number: 4
#       inverted: yes

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 12
    num_leds: 30
    rgb_order: GRB
    name: "color LED"
    id: 'led'

binary_sensor:
  - platform: gpio
    pin:
      number: 13
    id: 'person_sensor'
    on_state:
#      当小时数在20点后以及8点之前(time.hour是从0到23，所以小时都要-1)，以及检测到有人经过的时候，打开灯
      then:
      - lambda: |-
          auto time = id(sntp_time).now();
          if (id(person_sensor).state == 1 && (time.hour > 19 || time.hour < 7)) {
            auto call = id(led).turn_on();
            call.perform();
          } else {
            auto call = id(led).turn_off();
            call.perform();
          }